{u'message': {u'chat': {u'first_name': u'Rostyslav',
                        u'id': 385671687,
                        u'last_name': u'Makhanko',
                        u'type': u'private',
                        u'username': u'rostik_makhanko'},
              u'date': 1505560368,
              u'from': {u'first_name': u'Rostyslav',
                        u'id': 385671687,
                        u'is_bot': False,
                        u'language_code': u'uk-UA',
                        u'last_name': u'Makhanko',
                        u'username': u'rostik_makhanko'},
              u'message_id': 16,
              u'text': u'Hello'},
 u'update_id': 572851405}
